#!/usr/bin/python2
# -*- coding: utf-8 -*

import random
import string
import sys

char_list = string.ascii_letters + string.digits 
password = ""
for i in range(int(sys.argv[1])):
    index = random.randint(0, len(char_list) - 1)
    password += char_list[index]

print(password)
